### PR TITLE
Adds deprecated warnings

### PR DESCRIPTION
**Pull request by cuducos**
Following a chat in private, I understand @vinibispo is willing to archive this plugin in favor of better alternatives out there. This PR adds deprecated warnings to futures we might remove in follow-up PRs.

### CODE REVIEW

**Comment by cuducos** [comment]
I have run `stylua` even with `-f .stylua.toml` but I can't get this CI check to pass. Any idea?

**Comment by vinibispo** [comment]
> I have run `stylua` even with `-f .stylua.toml` but I can't get this CI check to pass. Any idea?

Yes, I was into stylua action documentation, and it seems they updated
```yml
  stylua:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua tests/ruby_nvim -f .stylua.toml

```

**Comment by cuducos** [comment]
It keeps red after b096dae

**Comment by vinibispo** [comment]
> It keeps red after [b096dae](https://github.com/vinibispo/ruby.nvim/commit/b096dae3f1901eac6522702d7f969c2858e9a4f6)

Sorry, I mean:
```yml
    - uses: actions/checkout@v3
    - uses: JohnnyMorganz/stylua-action@v2
```
Because stylua-action was updated

**Comment by cuducos** [comment]
Yay, now it works!

**Comment by vinibispo** [comment]
Thanks so much

**Pull request merged**
