### PR TITLE
Adds :RubyTest command

### PR DESCRIPTION
**Pull request by cuducos**
This PR suggests an implementation for `:RubyTest` — ~~it is marked as draft because it is not working locally, it throws an _Executable not found_ error that I believe is not a `ruby.nvim` problem, but something from my local setup. Can anyone help me with that?~~ Fixed. Thanks, @ellisonleao!

**TLDR**
 
* `:RubyTest` runs the current test file or the test of the current file's [alternate](https://github.com/vinibispo/ruby.nvim/pull/1)
* `:RubyTest!` in a test file runs the test located at the cursor position

**Context**

* We added a `options.lua` to handle configuration plugins, so we can have different commands to execute the tests (for example, `require("ruby_nvim").setup({ test = "rspec" })` for Rspec).
* We added a `init.lua` to handle the `setup` call
* We moved the alternate logic to `utils.lua` so we use it in `:RubyAlternate` and in `:RubyTest[!]`

### CODE REVIEW

**Comment by cuducos** [comment]
@vinibispo, pretendo ainda extrair o `args` do _job_ do Plenary para configurações do usuário — se quiser aguardar para o _merge_, devo fazer isso nos próximos dias. Mas Isso pode ser um novo PR tb : )

**Comment by vinibispo** [comment]
Ok @cuducos

**Comment by cuducos** [comment]
Done. What do you think?

**Comment by vinibispo** [comment]
Better than before

**Pull request merged**
